name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project 'DYLiveStream/DYLiveStream.xcodeproj' -scheme 'DYLiveStream' -destination 'platform=iOS Simulator,name=iPhone8'
    #- name: Run tests
    # run: swift test -v
